.PHONY: container
container:
	docker build \
	-t $(CONTAINER_REGISTRY)/$(CONTAINER_REPOSITORY)/$(CONTAINER_NAME):$(BUILD_VERSION) \
	--build-arg BUILD_CONTAINER=$(CONTAINER_GO_BUILD) \
	--build-arg RELEASE_CONTAINER=$(CONTAINER_RELEASE_SUPPORT) \
	--build-arg BUILD_VERSION=$(BUILD_VERSION) \
	--build-arg CONTAINER_USER=$(CONTAINER_USER) \
	--build-arg CONTAINER_MAINTAINER=$(CONTAINER_MAINTAINER) \
	.

.PHONY: push-container
push-container:
	docker push \
	$(CONTAINER_REGISTRY)/$(CONTAINER_REPOSITORY)/$(CONTAINER_NAME):$(BUILD_VERSION)

